# Generated by Django 3.2 on 2021-05-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0002_pengajarstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajarstaff',
            name='jobs',
            field=models.CharField(choices=[('Kepala sekolah', 'Kepala sekolah'), ('Wakil kepala sekolah', 'wakil kepala sekolah'), ('Kepala staff tata usaha', 'kepala staff tata usaha'), ('Pengajar', 'pengajar'), ('Staff', 'staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pengajarstaff',
            name='picture',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
    ]
