# Generated by Django 3.2 on 2021-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0007_alter_jadwal_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='date_schedule',
            field=models.DateField(default='2021/05/19'),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='events',
            field=models.TextField(),
        ),
    ]
