# Generated by Django 3.2 on 2021-05-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0008_auto_20210519_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='tglstr',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
