# Generated by Django 3.2 on 2021-05-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0010_alter_jadwal_tglstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='date_schedule',
            field=models.DateField(),
        ),
    ]
