# Generated by Django 3.2 on 2021-05-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0011_alter_jadwal_date_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bar', models.CharField(max_length=100)),
                ('title_sub', models.CharField(max_length=100)),
                ('img_main', models.ImageField(upload_to='picture/')),
                ('title_about', models.CharField(max_length=100)),
                ('content_about', models.CharField(max_length=100)),
                ('email_about', models.EmailField(max_length=254)),
                ('phone_about', models.CharField(max_length=20)),
                ('img_about', models.ImageField(upload_to='picture/')),
            ],
        ),
    ]
