# Generated by Django 3.2 on 2021-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0012_pengaturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturan',
            name='content_about',
            field=models.CharField(max_length=2000),
        ),
    ]
