# Generated by Django 3.2 on 2021-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visimisi', '0013_alter_pengaturan_content_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturan',
            name='img_about',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='pengaturan',
            name='img_main',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
    ]
